### PR TITLE
REFORMAT ONLY

### PR DESCRIPTION
**Pull request by clemoule**
applied reformat to py4cast repo -> reformat udpate ?

### CODE REVIEW

**Comment by A669015** [comment]
Did you execute `reformat.sh` with an up-to-date lint env (cf https://github.com/meteofrance/py4cast/blob/main/requirements_lint.txt) ?
If yes, I am very surprised the CI/CD didn't block the last PRs.

**Comment by clemoule** [comment]
requirements_lint.txt is up to date. I did in order : runai build; runai reformat and it doesnt modify the REFORMAT ONLY branch.

**Comment by clemoule** [comment]
Something is weird. Yesterday, I had ~20 reformated files hence this PR. Now I see that there are only 2 modified files. Im confused

**Comment by clemoule** [comment]
I think this update has already taken place in the origin repo. So when i synchronized yesterday it just deleted all the redundancies in the commit

**Comment by A669015** [comment]
> requirements_lint.txt is up to date. I did in order : runai build; runai reformat and it doesnt modify the REFORMAT ONLY branch.

My question was actually: is your `pip list` output aligned with your `requirements_lint.txt`, and particularly do you have `bandit==1.7.10` in your pip env

**Pull request closed without merging**
