### PR TITLE
fix np.load with memory mapping

### PR DESCRIPTION
**Pull request by Sakodad**
The use of np.memmap changes the data type (need to save the npy files to rbf files before using np.memmap). One solution : replace the np.memmap by np.load with memory mapping mode.

### CODE REVIEW

**Review by flyIchtus — APPROVED** [review]
Any impact on perfs ?

**Review by CorentinSeznec — APPROVED** [review]

**Comment by cbovalo** [comment]
There is a user warning when converting memmap Numpy arrays to Torch tensors : 
`UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /opt/conda/conda-bld/pytorch_1716905979055/work/torch/csrc/utils/tensor_numpy.cpp:206.)`
Maybe we can just return a copy of the Numpy array. What do you think ?

**Comment by Sakodad** [comment]
> There is a user warning when converting memmap Numpy arrays to Torch tensors : `UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /opt/conda/conda-bld/pytorch_1716905979055/work/torch/csrc/utils/tensor_numpy.cpp:206.)` Maybe we can just return a copy of the Numpy array. What do you think ?

In fact if we convert directly the numpy.memmap to tensor, we get the userwarning, but here, the mmap only serves to avoid loading the memory at opening. As soon as it is load,  there is a crop inside the numpy_memmap of the portion needed, and therefore the data_array returned is a classic numpy.ndarray which goes into tensor without problem.
Capture d’écran du 2024-09-30 11-49-07

**Comment by colon3ltocard** [comment]
> > There is a user warning when converting memmap Numpy arrays to Torch tensors : `UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /opt/conda/conda-bld/pytorch_1716905979055/work/torch/csrc/utils/tensor_numpy.cpp:206.)` Maybe we can just return a copy of the Numpy array. What do you think ?
> 
> In fact if we convert directly the numpy.memmap to tensor, we get the userwarning, but here, the mmap only serves to avoid loading the memory at opening. As soon as it is load, there is a crop inside the numpy_memmap of the portion needed, and therefore the data_array returned is a classic numpy.ndarray which goes into tensor without problem. Capture d’écran du 2024-09-30 11-49-07

@Sakodad I think slicing a memory mapped numpy array still returns a memory mapped numpy array. Would you mind checking the type after slicing just to confirm ?
```python
print(isinstance(sliced, np.memmap))      # Output: False if not mmap
```

**Comment by Sakodad** [comment]
> ```python
> print(isinstance(sliced, np.memmap))
> ```

I have already checked, it returns False.

**Comment by cbovalo** [comment]
Ok. @CorentinSeznec you can merge the PR.

**Pull request merged**
